subgraphs:
  user:
    routing_url: http://localhost:4001
    schema:
      subgraph_url: http://localhost:4001
  product:
    routing_url: http://localhost:4002
    schema:
      subgraph_url: http://localhost:4002
